### ISSUE TITLE
Use official gcr.io/cloud-builders/kubectl builder

### ISSUE THREAD

**Issue by imjasonh** [kelseyhightower/pipeline-infrastructure-production#7]
[cloudbuild.yaml](https://github.com/kelseyhightower/pipeline-infrastructure-production/blob/master/cloudbuild.yaml) specifies two steps, one to generate a kube config, and another to invoke `kubectl` with that config.

This could be simplified to just use the [official kubectl builder](https://github.com/GoogleCloudPlatform/cloud-builders/tree/master/kubectl) like so:

```
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '--recursive', '-f', 'kubernetes']
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=${_CLOUDSDK_COMPUTE_ZONE}'
      - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLOUDSDK_CONTAINER_CLUSTER}'
```

The `kubectl` builder is `FROM gcr.io/cloud-builders/gcloud` and overrides the entrypoint to a [wrapper around `kubectl`](https://github.com/GoogleCloudPlatform/cloud-builders/blob/master/kubectl/kubectl.bash) which understands the `CLOUDSDK_COMPUTE_ZONE` and `CLOUDSDK_CONTAINER_CLUSTER` env vars and invokes `gcloud` to provide credentials.

If the `kubectl` builder doesn't meet all your needs, let us know and we can talk about adding more features.

Thanks for the great tutorials! :+1:
